"use client"

import { useEffect, useState } from "react"
import { useRouter, useSearchParams } from "next/navigation"
import { useAuth } from "@/context/AuthContext"
import { apiGet } from "@/lib/api/client"

type Lesion = { id: string; label: string; created_at: string }
type AppPreferences = {
  allergies: string | null
  dermatologist_notes: string | null
  primary_condition_id: string | null
  conditions: string[]
}
type Condition = { id: string; display_name: string }
type SkinEvent = {
  id: string
  lesion_id: string
  ts: string
  severity_0_4: number
  itch: number
  pain: number
  burning: number
  dryness: number
  stress: number
  sleep_hours: number
  sleep_quality: number
  notes: string | null
}
type Medication = {
  id: string
  name: string
  category: string
  dose: string | null
  frequency: string | null
  is_prescription: boolean
  active: boolean
}
type Profile = { display_name: string | null }

function avg(xs: number[]) {
  if (xs.length === 0) return null
  return xs.reduce((a, b) => a + b, 0) / xs.length
}

export default function SummaryPage() {
  const router = useRouter()
  const params = useSearchParams()
  const { user, loading } = useAuth()
  const lesionFilter = params.get("lesion")
  const from = params.get("from") ?? ""
  const to = params.get("to") ?? ""

  const [data, setData] = useState<{
    profile: Profile | null
    prefs: AppPreferences | null
    conditions: Condition[]
    lesions: Lesion[]
    events: SkinEvent[]
    meds: Medication[]
  } | null>(null)

  useEffect(() => {
    if (!loading && !user) router.replace("/login?next=/export/summary")
  }, [user, loading, router])

  useEffect(() => {
    if (!user) return
    Promise.all([
      apiGet<Profile>("/api/profile").catch(() => ({ display_name: null })),
      apiGet<AppPreferences>("/api/app-preferences").catch(() => null),
      apiGet<Condition[]>("/api/conditions").catch(() => []),
      apiGet<Lesion[]>("/api/lesions"),
      apiGet<SkinEvent[]>("/api/skin-events?limit=1000"),
      apiGet<Medication[]>("/api/medications?active=true"),
    ]).then(([profile, prefs, conditions, lesions, events, meds]) => {
      setData({ profile, prefs, conditions, lesions, events, meds })
    })
  }, [user])

  if (!data) return <div className="p-8">Loading…</div>

  const filteredLesions = lesionFilter
    ? data.lesions.filter((l) => l.id === lesionFilter)
    : data.lesions

  const filteredEvents = data.events.filter((e) => {
    if (lesionFilter && e.lesion_id !== lesionFilter) return false
    const ts = e.ts.slice(0, 10)
    if (from && ts < from) return false
    if (to && ts > to) return false
    return true
  })

  const primary = data.conditions.find(
    (c) => c.id === data.prefs?.primary_condition_id,
  )
  const otherConds = (data.prefs?.conditions ?? []).filter(
    (id) => id !== data.prefs?.primary_condition_id,
  )

  return (
    <div className="mx-auto max-w-3xl p-6 print:p-0 bg-white">
      <div className="flex justify-between items-start print:hidden mb-4">
        <div className="text-sm text-slate-500">
          Use Print → Save as PDF to export or share.
        </div>
        <button
          onClick={() => window.print()}
          className="rounded bg-cyan-700 px-3 py-1.5 text-white text-sm"
        >
          Print / Save as PDF
        </button>
      </div>

      <div className="border-b border-slate-200 pb-4 mb-4">
        <h1 className="text-2xl font-semibold">SkinTrack+ Clinician Summary</h1>
        <div className="text-sm text-slate-600">
          Patient: {data.profile?.display_name ?? "—"}
          {"  ·  "}Generated: {new Date().toISOString().slice(0, 10)}
          {from || to ? `  ·  Range: ${from || "…"} to ${to || "…"}` : ""}
        </div>
        <p className="mt-2 text-xs text-amber-700">
          This is a self-tracking report generated by the patient. It is not a
          medical record and has not been validated as a diagnostic instrument.
        </p>
      </div>

      <section className="mb-4">
        <h2 className="font-semibold mb-1">Conditions</h2>
        <div className="text-sm">
          Primary: {primary?.display_name ?? "—"}
        </div>
        {otherConds.length > 0 && (
          <div className="text-sm text-slate-600">
            Other:{" "}
            {otherConds
              .map(
                (id) =>
                  data.conditions.find((c) => c.id === id)?.display_name ?? id,
              )
              .join(", ")}
          </div>
        )}
        {data.prefs?.allergies && (
          <div className="text-sm mt-1">
            <strong>Allergies:</strong> {data.prefs.allergies}
          </div>
        )}
        {data.prefs?.dermatologist_notes && (
          <div className="text-sm mt-1">
            <strong>Clinic notes:</strong> {data.prefs.dermatologist_notes}
          </div>
        )}
      </section>

      <section className="mb-4">
        <h2 className="font-semibold mb-1">Active medications &amp; remedies</h2>
        {data.meds.length === 0 && (
          <div className="text-sm text-slate-500">None recorded.</div>
        )}
        <ul className="list-disc pl-5 text-sm">
          {data.meds.map((m) => (
            <li key={m.id}>
              <strong>{m.name}</strong> · {m.category.replace("_", " ")}
              {m.dose ? ` · ${m.dose}` : ""}
              {m.frequency ? ` · ${m.frequency}` : ""}
              {m.is_prescription ? " · Rx" : ""}
            </li>
          ))}
        </ul>
      </section>

      <section className="mb-4">
        <h2 className="font-semibold mb-1">
          Lesion summary ({filteredLesions.length})
        </h2>
        {filteredLesions.map((l) => {
          const le = filteredEvents.filter((e) => e.lesion_id === l.id)
          return (
            <div
              key={l.id}
              className="border border-slate-200 rounded p-3 mb-2 text-sm"
            >
              <div className="font-medium">{l.label}</div>
              <div className="text-xs text-slate-500">
                Tracked since {l.created_at.slice(0, 10)} · {le.length} events
              </div>
              <div className="grid grid-cols-4 gap-2 mt-2 text-xs">
                <Stat label="Avg severity" v={avg(le.map((e) => e.severity_0_4))} />
                <Stat label="Avg itch" v={avg(le.map((e) => e.itch))} />
                <Stat label="Avg pain" v={avg(le.map((e) => e.pain))} />
                <Stat label="Avg sleep hrs" v={avg(le.map((e) => Number(e.sleep_hours)))} />
              </div>
            </div>
          )
        })}
      </section>

      <section className="mb-4">
        <h2 className="font-semibold mb-1">
          Events in range ({filteredEvents.length})
        </h2>
        <table className="w-full text-xs border-collapse">
          <thead>
            <tr className="border-b border-slate-200 text-left">
              <th className="py-1">Date</th>
              <th>Sev</th>
              <th>Itch</th>
              <th>Pain</th>
              <th>Sleep h</th>
              <th>Notes</th>
            </tr>
          </thead>
          <tbody>
            {filteredEvents
              .slice()
              .sort((a, b) => b.ts.localeCompare(a.ts))
              .slice(0, 60)
              .map((e) => (
                <tr key={e.id} className="border-b border-slate-100">
                  <td className="py-1">{e.ts.slice(0, 10)}</td>
                  <td>{e.severity_0_4}</td>
                  <td>{e.itch}</td>
                  <td>{e.pain}</td>
                  <td>{Number(e.sleep_hours).toFixed(1)}</td>
                  <td className="truncate max-w-[260px]">{e.notes ?? ""}</td>
                </tr>
              ))}
          </tbody>
        </table>
        {filteredEvents.length > 60 && (
          <div className="text-xs text-slate-500 mt-1">
            Showing 60 most recent of {filteredEvents.length} events.
          </div>
        )}
      </section>

      <footer className="mt-8 text-xs text-slate-500">
        SkinTrack+ is a self-tracking application. Data on this page was
        entered by the patient. Not a diagnostic tool. Not a medical device.
      </footer>
    </div>
  )
}

function Stat({ label, v }: { label: string; v: number | null }) {
  return (
    <div>
      <div className="text-slate-500">{label}</div>
      <div className="font-medium">{v == null ? "—" : v.toFixed(1)}</div>
    </div>
  )
}
